name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * 0"  # Every Sunday at 15:30 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Install codespell
      run: pip3 install codespell

    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-18 -P cmake/lint.cmake

    - name: Spell check
      if: always()
      run: cmake -P cmake/spell.cmake

  coverage:
    needs: [lint]

    runs-on: ubuntu-24.04

    env: { CXX: clang++-19 }

    # To enable coverage, delete the last line from the conditional below and
    # edit the "<name>" placeholder to your GitHub name.
    # If you do not wish to use codecov, then simply delete this job from the
    # workflow.
    if: github.repository_owner == '<name>'
      && false  # XXX disabled! CK

    steps:
    - uses: actions/checkout@v4

    # - name: Install LCov
    #   run: sudo apt-get update -q
    #     && sudo apt-get install lcov -q -y

    - name: Install Python
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-19
        vcvarsall: ${{ contains(matrix.os, 'windows') }}
        clangformat: true
        clangtidy: true
        cmake: 4.2.2
        ninja: 1.13.0
        gcovr: true

    - name: Configure
      run: cmake --preset=ci-coverage

    - name: Build
      run: cmake --build build/coverage -j 2

    - name: Test
      run: |
        cmake --install build/coverage --prefix $PWD/stagedir
        ctest --test-dir build/coverage --output-on-failure --no-tests=error -j 2

    - name: Process coverage info
      # run: cmake --build build/coverage -t coverage
      run: gcovr .

    # - name: Submit to codecov.io
    #   uses: codecov/codecov-action@v4
    #   with:
    #     file: build/coverage/coverage.info

  sanitize:
    needs: [lint]

    runs-on: ubuntu-24.04

    env: { CXX: clang++-19 }

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-19
        vcvarsall: ${{ contains(matrix.os, 'windows') }}
        clangformat: true
        clangtidy: true
        cmake: 4.2.2
        ninja: 1.13.0
        gcovr: true

    - name: Configure
      run: cmake --preset=ci-sanitize

    - name: Build
      run: cmake --build build/sanitize -j 2

    - name: Test
      env:
        ASAN_OPTIONS: "strict_string_checks=1:\
          detect_stack_use_after_return=1:\
          check_initialization_order=1:\
          strict_init_order=1:\
          detect_leaks=1"
        UBSAN_OPTIONS: print_stacktrace=1
      run: |
        cmake --install build/sanitize --prefix $PWD/stagedir
        ctest --test-dir build/sanitize --output-on-failure --no-tests=error -j 2

  test:
    needs: [lint]

    strategy:
      fail-fast: false

      matrix:
        os: [macos-15, ubuntu-24.04, windows-2022]
        include:
        - { os: macos-15, uname: Darwin }
        - { os: ubuntu-24.04, uname: Linux }
        - { os: windows-2022, uname: Windows }

        # TODO(CK):
        # type: [shared, static]
        # include:
        # - { type: shared, shared: YES }
        # - { type: static, shared: NO }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python
      if: matrix.os != 'macos-15'
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Install llvm
      if: matrix.os == 'macos-15'
      run: |
        brew install gcovr cmake ninja llvm
        export PATH=$(brew --prefix llvm)/bin:$PATH && echo "PATH=$PATH" >> $GITHUB_ENV
        export LDFLAGS=-L$(brew --prefix llvm)/lib/c++ -lc++abi -lc++ && echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Setup Cpp
      if: matrix.os == 'ubuntu-24.04'
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-19
        vcvarsall: ${{ contains(matrix.os, 'windows') }}
        clangformat: true
        clangtidy: true
        cmake: 4.2.2
        ninja: 1.13.0
        gcovr: true

    - name: Setup MultiToolTask
      if: matrix.os == 'windows-2022'
      run: |
        Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
        Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'
        Add-Content "$env:GITHUB_PATH" "$(Get-Location)\stagedir\bin"

    - name: update cmake and ninja
      if: matrix.os == 'windows-2022'
      run: pip install cmake ninja

    - name: Run workflow preset
      shell: bash
      run: |
        export hostSystemName=${{ matrix.uname }}
        perl -p -e "s/<hostSystemName>/${hostSystemName}/g;" .CMakeUserPresets.json > CMakeUserPresets.json
        uname || echo ${hostSystemName}
        cmake --version
        ninja --version
        cmake --workflow --preset=dev

  docs:
    # Deploy docs only when builds succeed
    needs: [sanitize, test]

    runs-on: ubuntu-24.04

    # To enable, first you have to create an orphaned gh-pages branch:
    #
    #    git switch --orphan gh-pages
    #    git commit --allow-empty -m "Initial commit"
    #    git push -u origin gh-pages
    #
    # Edit the <name> placeholder below to your GitHub name, so this action
    # runs only in your repository and no one else's fork. After these, delete
    # this comment and the last line in the conditional below.
    # If you do not wish to use GitHub Pages for deploying documentation, then
    # simply delete this job similarly to the coverage one.
    if: github.ref == 'refs/heads/master'
      && github.event_name == 'push'
      && github.repository_owner == '<name>'
      && false  # XXX disabled! CK

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments cmake ninja

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y

    - name: Build docs
      run: cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build"
        -P cmake/docs-ci.cmake

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
