name: Clang

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * 0"  # Every Sunday at 15:30 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        version: [20, 21]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/clang${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          # compiler: llvm-${{ matrix.version }}
          cmake: 4.2.0
          ninja: 1.13.0
          gcovr: true

      - name: Run test suite
        env:
          # CXX: clang++-${{ matrix.version }}
          CXX: clang++
          PATH: $HOME/.local/bin:$PATH
        run: |
          # export PATH=$HOME/.local/bin:$PATH
          make check
